name = "performance-monitor"
type = "javascript"
zone_id = "692e871ac481bbab14d73cbd3a90f137"
account_id = "d5e5859b3f99d48bc52d8a9140af8ef8"
route = "perf.snoozing.dev/*"
workers_dev = true
compatibility_date = "2021-10-24"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
